services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - jenkins-sonar-trivy-lab_sonarqube_data:/opt/sonarqube/data
      - jenkins-sonar-trivy-lab_sonarqube_extensions:/opt/sonarqube/extensions

  docker-agent:
    image: jenkins/inbound-agent:latest-jdk17
    container_name: jenkins-docker-agent
    depends_on:
      - jenkins
    environment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_AGENT_NAME=docker-agent-1
      - JENKINS_SECRET=REPLACE_ME
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - trivy-cache:/root/.cache

volumes:
  jenkins_home:
    external: true
  jenkins-sonar-trivy-lab_sonarqube_data:
    external: true
  jenkins-sonar-trivy-lab_sonarqube_extensions:
    external: true
  trivy-cache:
    external: true